#! /usr/bin/env python3


from accounts import Account

class Customer():
	def __init__(self):
		first_name = input("print your first name:  ")
		self._first_name = first_name
		self.accounts = []
		#self._last_name = last_name
		#self._DOB = DOB
		self.account_list = {}

	@property
	def name(self):
		return self._first_name


	def create_account(self, account_type):
		current_account = Account(account_type)
		current_account.deposit(1.00)
		(self.accounts).append(current_account)
		#self.account_list[current_account] = 1.00
		#(self.accounts).append(account_type)

	def show_accounts(self):
		print("in show accounts function")
		print("{} accounts".format(self._first_name))
		if not self.accounts:
			print("No accounts to show")
		else:
			for i in self.accounts:
				if(i == "None"):
					print("No accounts")
				else:
					print(i)

#	def __str__(self):
#		result = ""
#		if not self.account_list:
#			result += ("Cusomter: {} has No accounts to show".format(self._first_name))
#		else:
#			result = ("Customer: {}".format(self._first_name))
#			result = result + "\n" + "accounts" + "\n"
#			for key, value in self.account_list:
#				result = result + key + value
#				result += "\n"
#
#		return(result)


	def __str__(self):
		result = ""
		if not self.accounts:
			result += ("Customer: {} has No accounts to show".format(self._first_name))

		else:	
			#result = ("Customer: {}".format(self._first_name))
			#result = result + "\n" + "accounts" + "\n"
			for i in self.accounts:
				result = result + str(i) + str(i.account) + i.account_balance(i.account)
				result += "\n"
		return(result)






#	def account_list(self):
#		return(accounts)


	

	#@name.setter
	#def name(self, first_name):
	#	self._first_name = first_name

if __name__ == "__main__":
	aron = Customer()
#	print(aron.name)
#	aron.show_accounts()
#	print(aron)
	aron.create_account("Checking")
#	aron.create_account("Saving")
	print("This is after you add an account")
#	aron.show_accounts()
	print(aron)
